include:
  - path: docker/docker-compose.yml
    env_file: docker/.env

services:
  app:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - ./apps/web:/app/apps/web
    ports:
      - 3000:3000
    env_file:
      - apps/web/.env
    environment:
      - SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
      - SUPABASE_URL=http://kong:8000
    depends_on:
      analytics:
        condition: service_healthy
