include:
  - path: ${INCLUDE_PATH:-.}/docker/docker-compose.yml
    env_file: 
      - ${INCLUDE_PATH:-.}/docker/.env
      - ${INCLUDE_PATH:-.}/.env

services:
  app:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - ./apps/web:/app/apps/web
    ports:
      - 3000:3000
    env_file:
      - apps/web/.env
      - ${INCLUDE_PATH:-.}/.env
    environment:
      - SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
      - SUPABASE_URL=http://kong:8000
    depends_on:
      - kong
